import typescriptEslint from '@typescript-eslint/eslint-plugin';
import html from 'eslint-plugin-html';
import tsParser from '@typescript-eslint/parser';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import js from '@eslint/js';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all,
});

export default [
  ...compat.extends('plugin:@typescript-eslint/recommended'),
  {
    plugins: {
      '@typescript-eslint': typescriptEslint,
      html,
    },

    languageOptions: {
      parser: tsParser,
    },

    settings: {
      'import/resolver': {
        node: {
          extensions: ['.ts', '.tsx'],
          moduleDirectory: ['node_modules', 'src', 'demo'],
        },
      },
    },

    rules: {
      '@typescript-eslint/no-unsafe-function-type': 'warn',
      '@typescript-eslint/no-unused-vars': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',

      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'lit/decorators.js',
              importNames: ['customElement'],
              message:
                "Import customElement from '@src/util/custom-element' instead, so a tag already claimed by another bundle of this package is skipped rather than throwing.",
            },
            {
              name: 'lit/decorators/custom-element.js',
              importNames: ['customElement'],
              message:
                "Import customElement from '@src/util/custom-element' instead, so a tag already claimed by another bundle of this package is skipped rather than throwing.",
            },
          ],
        },
      ],
    },
  },
  {
    ignores: [
      '**/*.js',
      '**/*.mjs',
      '**/*.d.ts',
      '.claude/',
      '.wireit/',
      // Generated by `pnpm run strings:build`. Its eslint-disable comments go
      // unused, so `eslint --fix` would strip them and leave the file out of
      // step with what the build writes.
      'src/locales/*.ts',
      '!src/locales/*.test.ts',
    ],
  },
  {
    files: ['**/*.test.ts'],
    rules: {
      '@typescript-eslint/no-unused-expressions': 'off',
    },
  },
  {
    // Only the demo app calls configureLocalization (demo/demo-localization.ts).
    // @lit/localize throws if it's configured twice, so this package's own
    // source never does. Test files are exempt: they stand in for the app to
    // exercise a published locale module on its own.
    files: ['src/**/*.ts'],
    ignores: ['src/**/*.test.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'lit/decorators.js',
              importNames: ['customElement'],
              message:
                "Import customElement from '@src/util/custom-element' instead, so a tag already claimed by another bundle of this package is skipped rather than throwing.",
            },
            {
              name: 'lit/decorators/custom-element.js',
              importNames: ['customElement'],
              message:
                "Import customElement from '@src/util/custom-element' instead, so a tag already claimed by another bundle of this package is skipped rather than throwing.",
            },
            {
              name: '@lit/localize',
              importNames: ['configureLocalization'],
              message:
                'Only the demo app (demo/demo-localization.ts) calls configureLocalization. @lit/localize throws if configured twice, so this package never does.',
            },
          ],
        },
      ],
    },
  },
];
