/**
 * Builds the published icon modules in `src/icons/` from the SVG sources in
 * `icons/`.
 *
 * Each `icons/<name>.svg` produces two files:
 *
 * - `src/icons/<name>.ts`, whose default export is a lit `svg` template. It
 *   imports nothing but `svg` from lit, so a page that imports one icon loads
 *   that icon and nothing else.
 * - `src/icons/<name>.svg`, a copy of the source, so the `build` step's rsync
 *   publishes it next to the module for use outside lit.
 *
 * The root `<svg>` of the template is decorative by default (`aria-hidden`,
 * not focusable), painted with `currentColor`, and sized at `1em` so it
 * follows the surrounding font size.
 */
import {
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const sourceDir = join(root, 'icons');
const outputDir = join(root, 'src', 'icons');

const KEBAB_CASE = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const HEADER =
  '// Generated by scripts/build-icons.mts from icons/<name>.svg. Do not edit.\n';

/** Attributes the generator sets itself, so a source's own copy is dropped. */
const MANAGED_ATTRIBUTES = new Set([
  'width',
  'height',
  'fill',
  'xmlns',
  'aria-hidden',
  'focusable',
]);

function fail(message: string): never {
  throw new Error(`build-icons: ${message}`);
}

/** Strips the XML prolog, doctype and comments that precede the root. */
function stripPrologue(source: string): string {
  return source
    .replace(/<\?xml[\s\S]*?\?>/g, '')
    .replace(/<!DOCTYPE[\s\S]*?>/gi, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .trim();
}

function parseAttributes(source: string): [string, string][] {
  const attributes: [string, string][] = [];
  for (const match of source.matchAll(
    /([^\s=/]+)\s*=\s*("([^"]*)"|'([^']*)')/g,
  )) {
    attributes.push([match[1], match[3] ?? match[4]]);
  }
  return attributes;
}

function buildModule(name: string, raw: string): string {
  const source = stripPrologue(raw);
  const match = source.match(/^<svg(\s[^>]*)?>([\s\S]*)<\/svg>$/);
  if (!match) {
    fail(`${name}.svg must be a single <svg> element`);
  }
  const attributes = parseAttributes(match[1] ?? '');
  const viewBox = attributes.find(([key]) => key === 'viewBox')?.[1];
  if (!viewBox) {
    fail(`${name}.svg has no viewBox on its root <svg>`);
  }
  const inner = match[2].trim();
  if (source.includes('`') || source.includes('${') || source.includes('\\')) {
    fail(`${name}.svg contains a backtick, "\${" or backslash`);
  }
  if (/<script[\s>]/i.test(source) || /\son[a-z]+\s*=/i.test(source)) {
    fail(`${name}.svg contains a script or an event handler`);
  }

  const kept = attributes
    .filter(([key]) => !MANAGED_ATTRIBUTES.has(key))
    .map(([key, value]) => `${key}="${value}"`);
  const rootAttributes = [
    'xmlns="http://www.w3.org/2000/svg"',
    ...kept,
    'width="1em"',
    'height="1em"',
    'fill="currentColor"',
    'aria-hidden="true"',
    'focusable="false"',
  ].join(' ');

  return `${HEADER}import { svg } from 'lit';

export default svg\`<svg ${rootAttributes}>${inner}</svg>\`;
`;
}

const files = readdirSync(sourceDir).filter((file) => !file.startsWith('.'));
const seen = new Set<string>();
const built: { name: string; raw: string; module: string }[] = [];

for (const file of files.sort()) {
  if (!file.endsWith('.svg')) {
    fail(`icons/${file} is not an .svg file`);
  }
  const name = basename(file, '.svg');
  if (!KEBAB_CASE.test(name)) {
    fail(`icons/${file} has to be named in kebab-case, like "caret-open.svg"`);
  }
  if (seen.has(name)) {
    fail(`duplicate icon name "${name}"`);
  }
  seen.add(name);
  const raw = readFileSync(join(sourceDir, file), 'utf8');
  built.push({ name, raw, module: buildModule(name, raw) });
}

rmSync(outputDir, { recursive: true, force: true });
mkdirSync(outputDir, { recursive: true });
for (const { name, raw, module } of built) {
  writeFileSync(join(outputDir, `${name}.ts`), module);
  writeFileSync(join(outputDir, `${name}.svg`), raw);
}
console.log(`icons: ${built.length} built`);
